'use client';

import { AnalysisResult } from '@/lib/types';
import jsPDF from 'jspdf';
import { saveAs } from 'file-saver';

interface ExportButtonsProps {
    result: AnalysisResult | null;
}

export function ExportButtons({ result }: ExportButtonsProps) {
    if (!result) return null;

    const exportTXT = () => {
        const content = `OSINT VISION - ANALYSIS REPORT
Generated: ${new Date(result.timestamp).toLocaleString()}
Mode: ${result.mode.toUpperCase()}

${result.analysis}

---
Generated by OSINT Vision
https://osint-vision.vercel.app
`;
        const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
        saveAs(blob, `osint-analysis-${result.mode}-${Date.now()}.txt`);
    };

    const exportJSON = () => {
        const data = {
            timestamp: result.timestamp,
            mode: result.mode,
            analysis: result.analysis,
            exifData: result.exifData,
            confidence: result.confidence,
            generatedBy: 'OSINT Vision',
            url: 'https://osint-vision.vercel.app'
        };
        const blob = new Blob([JSON.stringify(data, null, 2)], {
            type: 'application/json'
        });
        saveAs(blob, `osint-analysis-${result.mode}-${Date.now()}.json`);
    };

    const exportPDF = () => {
        const doc = new jsPDF();

        // Header
        doc.setFontSize(22);
        doc.setTextColor(0, 50, 0); // Dark Green
        doc.text('OSINT VISION', 20, 20);

        doc.setFontSize(14);
        doc.setTextColor(0);
        doc.text('Image Intelligence Analysis Report', 20, 30);

        // Metadata block
        doc.setFillColor(240, 240, 240);
        doc.rect(20, 35, 170, 20, 'F');

        doc.setFontSize(10);
        doc.setTextColor(50);
        doc.text(`Generated: ${new Date(result.timestamp).toLocaleString()}`, 25, 42);
        doc.text(`Mode: ${result.mode.toUpperCase()}`, 25, 49);

        // Analysis content
        doc.setFontSize(11);
        doc.setTextColor(0);

        // Simple split for now since jspdf-autotable is better for tables, but text works for basic reports
        const splitText = doc.splitTextToSize(result.analysis, 170);
        doc.text(splitText, 20, 65);

        // Footer
        doc.setFontSize(8);
        doc.setTextColor(150);
        doc.text(
            'Generated by OSINT Vision | https://osint-vision.vercel.app',
            20,
            doc.internal.pageSize.height - 10
        );

        doc.save(`osint-analysis-${result.mode}-${Date.now()}.pdf`);
    };

    return (
        <div className="flex gap-2 justify-end mt-4">
            <button
                onClick={exportPDF}
                className="px-4 py-2 bg-red-600 hover:bg-red-700 text-white rounded flex items-center gap-2 text-sm font-medium transition-colors"
            >
                <span>📄</span> Export PDF
            </button>

            <button
                onClick={exportJSON}
                className="px-4 py-2 bg-yellow-600 hover:bg-yellow-700 text-white rounded flex items-center gap-2 text-sm font-medium transition-colors"
            >
                <span>📊</span> Export JSON
            </button>

            <button
                onClick={exportTXT}
                className="px-4 py-2 bg-blue-600 hover:bg-blue-700 text-white rounded flex items-center gap-2 text-sm font-medium transition-colors"
            >
                <span>📝</span> Export TXT
            </button>
        </div>
    );
}
